name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version

      - name: Build Docker image
        run: docker build -t martinshishkov/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true martinshishkov/docker-react npm run test -- --coverage
